name: blockjitsu
socket:
  server_key: i5XxhNlXjs
runtime:
  http_key: 7Uc4v72WZb
session:
  encryption_key: jm8WXt073a
  refresh_encryption_key: BVOiKgq6ha
console:
  username: nully
  password: 1n:Odr+Y^*(`WuwZ6Ui#rV1||?d-3Q
  signing_key: si7fAFS86sZ
